# Generated by Django 3.1.4 on 2020-12-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_heading', models.TextField(default='default heading...')),
                ('c_paragraphs', models.TextField(default='default content...')),
            ],
        ),
    ]
