# Generated by Django 3.1.4 on 2020-12-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='h_image',
            field=models.ImageField(blank=True, default='templates/images/discuss.jpg', null=True, upload_to='templates/'),
        ),
    ]
