# Generated by Django 3.1.4 on 2020-12-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_h_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='h_image',
            field=models.ImageField(blank=True, default='templates/images/discuss.jpg', null=True, upload_to=''),
        ),
    ]
