# Generated by Django 3.1.4 on 2020-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201218_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='h_image',
            field=models.ImageField(blank=True, default='templates/images/discuss.jpg', height_field='image_width', null=True, upload_to='', width_field='image_height'),
        ),
    ]
