# Generated by Django 3.1.4 on 2020-12-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201218_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='h_image',
            field=models.ImageField(default='templates/images/discuss.jpg', height_field='image_width', null=True, upload_to='', width_field='image_height'),
        ),
    ]
